### ISSUE TITLE
CRESIL annotation

### ISSUE THREAD

**Issue by HaoWangLYL** [visanuwan/cresil#1]
when I use a genome which was assemblied and annotation by myself.
And I product the repeat.anno file by RepeatMASKRE, but the format of this is different from the file in your benckmack(human and mouse from UCSC), And I tried to change the format to making it be similar to your file but noyt work....
Do your kown how can I make the de novo repeat_anno be the input in your software?
this is the raw file of mine:
   SW   perc perc perc  query     position in query              matching               repeat               position in repeat
 score   div. del. ins.  sequence  begin    end          (left)   repeat                 class/family     begin   end    (left)      ID

   226    2.6  0.0  0.0  Chr1             5       64 (45016410) C TE_00001596            DNA/Helitron      (1977)   2116    2078      1 *
   230    2.7  0.0  0.0  Chr1            36       72 (45016402) C TE_00002821            DNA/Helitron      (2253)   1096    1060      2  
   226    2.6  0.0  0.0  Chr1            75      134 (45016340) C TE_00001596            DNA/Helitron      (1977)   2116    2078      1  
   226    2.6  0.0  0.0  Chr1           208      246 (45016228) C TE_00001596            DNA/Helitron      (1977)   2116    2078      1  
   235    1.4  0.0  0.0  Chr1           312      390 (45016084) C TE_00001596            DNA/Helitron      (1977)   2116    2078      1 *
   239    2.6  0.0  0.0  Chr1           387      449 (45016025) C TE_00001596            DNA/Helitron      (1974)   2119    2078      1  
and this is the file which I changed for your software
gap1    226     2.6     0.0     0.0     Chr1    5       64      -45016410       -       TE_00001596     Helitron        DNA     (1977)  2116    2078    1
gap1    230     2.7     0.0     0.0     Chr1    36      72      -45016402       -       TE_00002821     Helitron        DNA     (2253)  1096    1060    2
gap1    226     2.6     0.0     0.0     Chr1    75      134     -45016340       -       TE_00001596     Helitron        DNA     (1977)  2116    2078    1
gap1    226     2.6     0.0     0.0     Chr1    208     246     -45016228       -       TE_00001596     Helitron        DNA     (1977)  2116    2078    1
gap1    235     1.4     0.0     0.0     Chr1    312     390     -45016084       -       TE_00001596     Helitron        DNA     (1977)  2116    2078    1
gap1    239     2.6     0.0     0.0     Chr1    387     449     -45016025       -       TE_00001596     Helitron        DNA     (1974)  2119    2078    1
gap1    226     2.6     0.0     0.0     Chr1    418     463     -45016011       -       TE_00001596     Helitron        DNA     (1977)  2116    2078    1

Thanks for your help~

**Comment by visanuwan** [comment]
@HaoWangLYL The format used for CReSIL is from a UCSC hgTables, which has 17 columns.
You can change your [RepeatMasker results](https://www.repeatmasker.org/webrepeatmaskerhelp.html) according to the UCSC schema [here](https://genome.ucsc.edu/cgi-bin/hgTables).

**Comment by HaoWangLYL** [comment]
> 

yes, I had tried to change my results to your format but not work,there are something wrong. and I found in your script "annnotate.py", for rmsk.bed,the useful column is [5,6 7, 10, 11,12] which means "'chrom','start','end','repName','repClass','repFamily','" So I pay particular attention to these five columns.
this is the format which I changed according to the UCSC.
gap1 226 2.6 0.0 0.0 Chr1 5 64 -45016410 - TE_00001596 Helitron DNA (1977) 2116 2078 1
gap1 230 2.7 0.0 0.0 Chr1 36 72 -45016402 - TE_00002821 Helitron DNA (2253) 1096 1060 2
gap1 226 2.6 0.0 0.0 Chr1 75 134 -45016340 - TE_00001596 Helitron DNA (1977) 2116 2078 1
gap1 226 2.6 0.0 0.0 Chr1 208 246 -45016228 - TE_00001596 Helitron DNA (1977) 2116 2078 1
gap1 235 1.4 0.0 0.0 Chr1 312 390 -45016084 - TE_00001596 Helitron DNA (1977) 2116 2078 1
gap1 239 2.6 0.0 0.0 Chr1 387 449 -45016025 - TE_00001596 Helitron DNA (1974) 2119 2078 1
gap1 226 2.6 0.0 0.0 Chr1 418 463 -45016011 - TE_00001596 Helitron DNA (1977) 2116 2078 1
and the is the wrong output
/public/home/anaconda3/envs/cresil/lib/python3.8/site-packages/cresil/cli/annotate.py:17: DtypeWarning: Columns (4,7,8,14) have mixed types. Specify dtype option on import or set low_memory=False.
  rmsk = pd.read_csv(fname, header=None, sep='\t', quotechar='"', on_bad_lines='skip')
Traceback (most recent call last):
  File "/public/home/anaconda3/envs/cresil/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "/public/home/anaconda3/envs/cresil/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/public/home/anaconda3/envs/cresil/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'int

**Comment by visanuwan** [comment]
@HaoWangLYL The sample of your data and its format works fine on my end.
Is it possible for you to share a full RepeatMasker result?

**Comment by HaoWangLYL** [comment]
> 

oh ,i had solved this problem.
however, I have new wrong about  plot . for echo sample I use , only ec1 can be plotted.....

**Comment by HaoWangLYL** [comment]
> @HaoWangLYL The sample of your data and its format works fine on my end. Is it possible for you to share a full RepeatMasker result?

i had solved all the problem, thank you very much~~~~~~

**Comment by khugmat** [comment]
> > @HaoWangLYL The sample of your data and its format works fine on my end. Is it possible for you to share a full RepeatMasker result?
> 
> i had solved all the problem, thank you very much~~~~~~

How you solved problem?
