### ISSUE TITLE
Definition of eccdna_status

### ISSUE THREAD

**Issue by 20191600** [visanuwan/cresil#3]
Hello there,
I am confued by  the definition of 'eccdna_status' in the output of identify_wgls. What's the difference between cyclic and non-cyclic eccDNA? How could a eccDNA be non-cyclic?

Thanks a lot.

**Comment by visanuwan** [comment]
@20191600 The non-cyclic eccDNAs could be the artifacts of the prediction or the quality of data.
The goal of CReSIL is to capture all possible results and it's up to the user to define the cutoff.

**Comment by 20191600** [comment]
I suppose cyclic eccDNA is all i need. Thanks for answering.
